---
swagger: '2.0'
info:
  version: 1.0.0
  title: Partners API
  description: |
    Returns information about the Toast restaurants that a partner 
    API client can access.
  contact:
    name: Toast developer support
schemes:
  - https

host: toast-api-server
basePath: /partners/v1
consumes:
  - application/json
produces:
  - application/json
definitions:
  PartnerAccessExternalRep:
    type: object
    description: |
      Information about a Toast platform restaurant.
    properties:
      restaurantGuid:
        type: string
        format: uuid
        description: |
          The unique Toast POS identifier for the restaurant.
      managementGroupGuid:
        type: string
        format: uuid
        description: |
          The guid of the management group containing the restaurant.
      restaurantName:
        type: string
        description: |
          The human-readable name of the restaurant location.
      locationName:
        type: string
        description: |
          The identifier of a specific restaurant location, set on the 
          *Restaurant Info* page of the Toast administration back-end. 
          For example, a restaurant group might assign a location code 
          such as #1234 to a specific location.
      createdByEmailAddress:
        type: string
        description: |
          The email address of the restaurant employee who connected 
          the restaurant to the partner that made the request to the 
          `/restaurants` endpoint, or who edited the connection 
          details.
      externalGroupRef:
        type: string
        description: |
          An identifier for the restaurant group that is recognized by 
          the partner that made the request to the `/restaurants` 
          endpoint. This information is entered by the restaurant 
          administrator. If you need information about the restaurant 
          group in this data string, you instruct the restaurant 
          administrator to enter it in the Toast platform 
          configuration for the integration partner connection.
      externalRestaurantRef:
        type: string
        description: |
          An identifier for the restaurant location that is recognized 
          by the partner that made the request to the `/restaurants` 
          endpoint. This information is entered by the restaurant 
          administrator. If you need information about the restaurant 
          location in this data string, you instruct the restaurant 
          administrator to enter it in the Toast platform
          configuration for the integration partner connection.
      modifiedDate:
        type: string
        format: date-time
        description: |
          The most recent date and time that the partner connection
          was edited in epoch time (milliseconds since 1970-01-01 00:00:00).
      createdDate:
        type: string
        format: date-time
        description: |
          The date and time that the partner connection was created in epoch time (milliseconds since 1970-01-01 00:00:00).
      isoModifiedDate:
        type: string
        description: |
          The most recent date and time that the partner connection
          was edited in ISO8601 format.
      isoCreatedDate:
        type: string
        description: |
          The date and time that the partner connection was created in ISO8601 format.

  PartnerAccessExternalWebhookRep:
    type: object
    description: |
      Information about a Toast platform restaurant.
    properties:
      restaurantGuid:
        type: string
        format: uuid
        description: |
          The unique Toast POS identifier for the restaurant.
      managementGroupGuid:
        type: string
        format: uuid
        description: |
          The guid of the management group containing the restaurant.
      restaurantName:
        type: string
        description: |
          The human-readable name of the restaurant location.
      locationName:
        type: string
        description: |
          The identifier of a specific restaurant location, set on the
          *Restaurant Info* page of the Toast administration back-end.
          For example, a restaurant group might assign a location code
          such as #1234 to a specific location.
      externalGroupRef:
        type: string
        description: |
          An identifier for the restaurant group that is recognized by
          the partner that made the request to the `/restaurants`
          endpoint. This information is entered by the restaurant
          administrator. If you need information about the restaurant
          group in this data string, you instruct the restaurant
          administrator to enter it in the Toast platform
          configuration for the integration partner connection.
      externalRestaurantRef:
        type: string
        description: |
          An identifier for the restaurant location that is recognized
          by the partner that made the request to the `/restaurants`
          endpoint. This information is entered by the restaurant
          administrator. If you need information about the restaurant
          location in this data string, you instruct the restaurant
          administrator to enter it in the Toast platform
          configuration for the integration partner connection.
      modifiedDate:
        type: string
        format: date-time
        description: |
          The most recent date and time that the partner connection
          was edited in epoch time (milliseconds since 1970-01-01 00:00:00).
      createdDate:
        type: string
        format: date-time
        description: |
          The date and time that the partner connection was created in epoch time (milliseconds since 1970-01-01 00:00:00).
      isoModifiedDate:
        type: string
        description: |
          The most recent date and time that the partner connection
          was edited in ISO8601 format.
      isoCreatedDate:
        type: string
        description: |
          The date and time that the partner connection was created in ISO8601 format.
      createdByFirstName:
        type: string
        description: |
          The first name of the user who initiated the event.
      createdByLastName:
        type: string
        description: |
          The last name of the user who initiated the event.
      createdByEmailAddress:
        type: string
        description: |
          The email address of the restaurant employee who connected
          the restaurant to the partner that made the request to the
          `/restaurants` endpoint, or who edited the connection
          details.
      createdByPhoneNumber:
        type: string
        description: |
          The phone number of the user who initiated the event.
      restaurantPhoneNumber:
        type: string
        description: |
          The phone number of the restaurant.
      restaurantAddressLine1:
        type: string
        description: |
          The physical address of the restaurant location.
      restaurantAddressLine2:
        type: string
        description: |
          Optional additional physical address of the restaurant location.
      restaurantCity:
        type: string
        description: |
          The city in which the restaurant is located.
      restaurantState:
        type: string
        description: |
          The state in which the restaurant is located.
      restaurantZipCode:
        type: string
        description: |
          The zip code of the restaurant location.
      restaurantLatitude:
        type: string
        description: |
          The latitude of the restaurant location.
      restaurantLongitude:
        type: string
        description: |
          The longitude of the restaurant location.

  PaginatedResponse:
    type: object
    description: |
      Returns responses with pagination. For this endpoint, includes the `results` object which houses an array of restaurant objects. The end of this response includes paginated details such as how many pages are included in the response, or the total amount of objects in the `results` arary. 
    properties:
      currentPageNum:
        type: integer
        description: |
          The active page within all repsonse pages. You can see the total amount of pages at the end of the response in the `lastPageNum` field. 
      results:
        type: array
        description: |
          An array that includes Toast restaurant data. 
        items:
          $ref: '#/definitions/PartnerAccessExternalRep'
      totalResultCount:
        type: integer
        description: |
          The total number of records returned.  
      pageSize:
        type: integer
        description: |
          The active page size used to display results. For example, if the `pageSize` query was added, the added number will match this value. 
      currentPageToken:
        type: string
        format: uuid
        description: |
          Token used to define the current page. 
      nextPageToken:
        type: string
        format: uuid
        description: |
          Token used to define the next page. 
      totalCount:
        type: integer
        description: |
          The total number of results within the response record. 
      nextPageNum:
        type: integer
        description: |
          The next available page in the data. `Null` if you've come to the last available page. 
      lastPageNum:
        type: integer
        description: |
          The last page number in the response data. 
      previousPageNum:
        type: integer
        description: |
          The page number for the page previous to your current page in sequential order. `Null` if there are no pages previous to your current page. 


paths:
  /restaurants:
    get:
      operationId: restaurantsGet
      summary: Get accessible restaurants
      description: |
        Returns an array of `PartnerAccessExternalRep` 
        objects that contain information about the Toast restaurants that a partner 
        API client can access. If a `lastModified` date is specified, the API returns 
        all objects that were created or modified after that date.
      produces:
        - application/json
      parameters:
        - name: lastModified
          description: |
            Limits the return data to restaurants that changed their 
            access configuration for a partner API client after a 
            specific date and time.
            
            Restaurants returned either:
            
            * Gave access to a partner API client for a partner 
              integration service after a specific date and time.
            
            * Modified the configuration for a partner integration 
              after a specific date and time. 
            
            You must specify the date and time as a UTC timestamp in 
            ISO 8601 format, for example: 
            `2020-03-01T00:00:00.000-0000`. URL encode the timestamp. 
            For example, `2020-03-01T00%3A00%3A00.000-0000`.
          in: query
          type: string
          format: date
          required: false
      responses:
        '200':
          description: Returns the list of external partner accesses
          schema:
            type: array
            items:
              $ref: '#/definitions/PartnerAccessExternalRep'
        '403':
          description: |
            Your Toast API client does not have permission to use the 
            `/restaurants` endpoint.
  /connectedRestaurants:
    get:
      operationId: connectedRestaurantsGet
      summary: Get connected restaurants
      description: |
        Returns an array as a `PaginatedResponse` and allows for further pagination of results. Use the `page` and `pagesize` queries to modify the amount of data shown, or the active page. 
        For example: 
        `?page=6` displays the sixth page of the response results. 
        `?pagesize=200` displays 200 lines of information. The default `pagesize` is 100. 
      produces:
        - application/json
      parameters:
        - name: lastModified
          description: |
            Limits the return data to restaurants that changed their 
            access configuration for a partner API client after a 
            specific date and time.
            
            Restaurants returned either:
            
            * Gave access to a partner API client for a partner 
            integration service after a specific date and time.
            
            * Modified the configuration for a partner integration 
            after a specific date and time. You must specify the date and time as a UTC timestamp in 
            ISO 8601 format, for example: 
            `2020-03-01T00:00:00.000-0000`. URL encode the timestamp. 
            For example, `2020-03-01T00%3A00%3A00.000-0000`.
          in: query
          type: string
          format: date
          required: false
      
      responses:
        '200':
          description: Returns the list of external partner accesses
          schema:
            type: array
            items:
              $ref: '#/definitions/PaginatedResponse'
        '403':
          description: |
            Your Toast API client does not have permission to use the 
            `/restaurants` endpoint.
